### ISSUE TITLE
Prevent the function deployment by everyone thanks to a token (or something else)

### ISSUE THREAD

**Issue by k33g** [fnproject/fn#1149] opened 2018-07-31 19:31 UTC
**Allow the function call to everyone, but leave the deployment accessible only to an administrator or a bot with the appropriate credentials**

A use case:

- I would like to provide API services to people throw the Fn server
- I will test and deploy the functions from a git repository thanks a GitLab runner (or Travis CI, or Atlassian pipeline or JenkinsFile):
  - so the runner will run the command `fn deploy --app`
  - or the command `fn run` for test

The runner would be the only way to deploy, so I need to be able to provide credentials to the runner thanks to an environment variable (and then to prevent anybody to deploy on the Fn server)

So,

1. I start the Fn server `FN_SECRET_TOKEN="ILovePanda" fn start`
2. I (or the runner) can deploy functions only with the token
3. Other people can only call the functions

**Comment by jgh-** [comment] 2018-07-31 21:26
maybe have it able to call a URI and expect something like 200 OK or 403 Forbidden?

**Comment by rdallman** [comment] 2018-08-01 18:32
Hi @k33g this setup should be possible via our extension mechanisms, for example https://github.com/fnproject/fn/blob/master/fnext/listeners.go#L47 could be used to block users from deploying functions without certain permissions. Users can use the `context.Context` to store certain items like a token or user id, which can be seeded by the http middleware we offer https://github.com/fnproject/fn/blob/master/fnext/middleware.go#L30. You may also use https://github.com/fnproject/fn/blob/master/fnext/listeners.go#L95 to attenuate permissions around function invocation itself. In core we have left this intentionally flexible. 

An example using some of these constructs may be found https://github.com/fnproject/ext-auth -- in itself it's not a perfect example for this (aside from no longer building), but it's easy to see how to set up a `main` to build a server with custom extensions added onto it to accomplish something like this.

since this issue is not a bug or feature request I am going to close it, however feel free to continue discussion here or in slack, it would be great to produce a document outlining how to accomplish this use case from this. thanks!

**Closed by rdallman** 2018-08-01 18:32 UTC

**Comment by k33g** [comment] 2018-08-01 20:13
@rdallman thank you for the message, but it seems that **ext-auth** project is no more compliant with the current version of **Fn**, I try before opening the issue
see the message in the Slack https://fnproject.slack.com/archives/C6FL02Q02/p1533061967000107

I'm not a Go developer (and probably some other users of **Fn**), so imho this issue is a feature request and it could be ease the adoption of **Fn** project

**Comment by rdallman** [comment] 2018-08-01 21:18
understood. here's an example that builds: https://github.com/fnproject/fn/blob/master/examples/middleware/main.go which may help be more illustrative -- the expectation for this feature though is very much that operators will have to build fn (using the go build chain) with their extensions added in to support things like authentication / permissions, among other things. we do need more examples out of the box for things like JWT (and we need to fix ext-auth) to help users do things like this but it's explicitly a non-goal to not have support for token-based auth (as implied) in core itself. we are doing similar for the service we are building on top of this, so this works but some tinkering is required :) thanks for opening this, and happy to help with this in slack to integrate your auth solution (have been following along)

**Comment by k33g** [comment] 2018-08-01 21:59
ok thanks for this @rdallman 
I will try, but I need to do my first baby steps in Go before ;)

**Comment by k33g** [comment] 2018-08-01 22:55
so, I understand the code of `main.go`, but for somebody that does not know Go (and the go build chain), it's not trivial
I tried:
```
go get github.com/fnproject/fn/api/server
go build ./middleware
```

and I get:
```
build output "middleware" already exists and is a directory
```

**Comment by rdallman** [comment] 2018-08-02 23:39
in dir from: https://github.com/fnproject/fn/tree/master/examples/middleware

```
$ go get -u
$ go build
$ ./middleware
```

`go build` works in a directory setting without needing to point it at any files. if the readme there doesn't work for whatever reason, we can fix it, but it should work ok.
