### ISSUE TITLE
Function definition should be an independent from the execution type

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#824] opened 2018-03-08 12:08 UTC
At this particular moment, each function has a `type` field that defines whether the function can be called synchronously or asynchronously. So, if I want to call a function in these two modes I have to define two separate routes one that could be `sync` and the other one is `async`. 

However, serverless defines itself as a replacement for the "local" function, so in most programming languages i can call the function as i want, so in most cases, there is no special definition/signature to tell to the programming language runtime whether a function is a sync or async (not taking into account Python's async/await feature, etc.) it's all about the way we execute that (goroutines, event loops, etc.).

From the UX perspective, it would be a good value-add to the process of calling the functions to make execution type configurable at the runtime.

There are couple ways to make execution type configurable:
 - HTTP header (`X-FN-TYPE`)
 - query parameter (`/r/{app}/{route}?fn_type=sync`)

**Comment by rdallman** [comment] 2018-03-08 16:54
dupe of https://github.com/fnproject/fn/pull/295 (though this has better motivation speech, thanks)

**Comment by rdallman** [comment] 2018-03-08 16:57
This one specifically could go hand-in-hand with https://github.com/fnproject/fn/issues/817 - function definition wouldn't have 'type' at all and will just be tied to an event (one way of looking at it)

**Comment by rdallman** [comment] 2018-06-26 02:10
done #1060

**Closed** 2018-06-26 02:11 UTC
Labels: for discussion
