### ISSUE TITLE
slots should dynamically check ram available

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#501] opened 2017-11-14 18:37 UTC
atm we're only gathering ram available upon startup. we should accurately take into account docker / fn / other process memory usage when allowing slots and likely leave some overhead for those things, as well (maybe cap at 90% usage or something). we should consider other heuristics for doling out slots (cpu, disk, ?) as well but that's potentially less urgent.

**Comment by skinowski** [comment] 2017-11-15 23:44
I've been looking at the code and wondering how to go about this. Considering cpu & disk (and possibly network IO limits) in future, I feel like we could continue using the similar strategy, except that ramToken becomes a more generic resource token.

There's also the issue of fetching the correct ram available across different platforms and environments.
I wonder if we should actually forgo trying to determine ram available (currently code only works for linux anyway(*)) and leave this to users who can set these limits (for children/siblings) in fn startup as 'max mem size', 'total disk weight or bps', 'total cpu or cpu shares', etc. (and perhaps network limits in future.)

@rdallman what do you think?

(*) For linux, current code has some issues. Besides hard coded numbers (easy fix), there's an issue of cgroup & docker in docker versus cgroup & docker bind mount, where I think cgroup limit may or may not apply.

**Comment by rdallman** [comment] 2017-11-16 01:10
in some sense it's true we really only care for production servers to set the limits properly and we could default turn them off. however, this was the case not so long ago and people testing fn ran into some fun surprises when 100 containers got launched on their laptops, so we should probably try to apply some limit by default, even if it's something arbitrary (we could just fix to 1GB of memory or something). but overall, don't think it's worth the time investment to support proper sizing across a bunch of platforms; unfortunately it's the case we don't have a service atm, so people have to think about this -- long term, I don't think this is the norm, this will be in prod realistically only on linux servers unless the infrastructure landscape changes significantly, quickly. 

fwiw we do support setting `docker run --memory 2GB fnproject/fn-server` properly already (if it works as intended). this seems possibly preferable to a separate environment variable that could mismatch with this value. 

the code we have seemed to me to work fine when running the binary against my host as well as the dind image we recommend. it's not perfect, but so long as it works ok in the dind image on osx & linux and the command we recommend to run that with doesn't use the docker bind mount, I think it's ok as is. the only bugaboo is the `MemAvailable` thing is relatively new (2 years new), otherwise not sure of concrete shortcomings (I think we could use MemFree+MemCached or something along those lines, as well, if we must).

**Comment by skinowski** [comment] 2017-11-16 01:19
ok, I slightly misunderstood this. "docker run --memory 2GB fnproject/fn-server" applies to fn-server *and* all spawned children & siblings. Not separately fn-server itself. :-)

**Comment by rdallman** [comment] 2017-11-16 01:22
hmm, we should be further limiting the child containers inside of `fn-server`, we're specifying the memory when we're creating them (this is configured on the route). this is being overwritten?

**Comment by rdallman** [comment] 2017-11-16 01:23
link: https://github.com/fnproject/fn/blob/master/api/agent/drivers/docker/docker.go#L103

**Comment by rdallman** [comment] 2017-11-16 01:28
in any event, that would be okay, no? if the max memory of the parent is 2GB then no child should be able to go over 2GB, either.

**Comment by skinowski** [comment] 2017-11-16 01:33
yes, it looks correct. I just misunderstood what we intended with the memory limit args between regular docker spawn vs dind. I thought the semantics would be different...

When I launch docker with sock bind, then I expected the memory arguments in docker-run to only apply to that container alone. But that makes things complicated (perhaps unnecessary), since then we'd need separate params for children. eg. A case, where I want to limit fn server itself to 200MB, but allow the children to use up to 4GB. As opposed to more dind expected behavior of 4GB for all (children + fn-server).

**Comment by skinowski** [comment] 2017-12-15 21:50
should I close this after #541 ?

**Closed by skinowski** 2017-12-15 21:50 UTC
