### ISSUE TITLE
Deploying fnproject on a system with docker and without fn installed

### ISSUE THREAD

**Issue by SaiNageswarS** [fnproject/fn#1404] opened 2019-02-14 14:10 UTC
I see once I deploy a fn app, a docker image is built and pushed to my repository. How can I start server directly from docker image without using fn?\

Tried following: 
```sh
docker run <image>
docker run -e FN_API_URL=http://127.0.0.1:8080 <image>
```

is giving error as "url scheme must be unix with a valid path"

**Comment by rdallman** [comment] 2019-02-14 17:48
to run the container locally `FN_LISTENER` must be present with a path to start a unix socket on, something like `unix:/tmp/sock.sock` - there's various other variables that the container may rely on, they may be found here: https://github.com/fnproject/docs/blob/master/fn/develop/fn-format.md - it's generally recommended to run fn locally in order to execute functions via fn, there's not a currently supported way to do this easily in the cli or elsewhere. closing since this is not a bug, feel free to continue discussion here or slack.

**Closed by rdallman** 2019-02-14 17:48 UTC

**Comment by SaiNageswarS** [comment] 2019-02-14 17:53
As I understand, fnproject/fnserver is an independent server providing routing, logging, queuing etc. For every app(collection of functions), a new docker container is spinned up.

On a trigger to fnserver, fnserver calls appropriate function in app container.

I'm able to deploy my function by building a container and submitting it to fnserver from source, however, I'm not able to find any way to deploy an existing app image to fnserver.

**Comment by rdallman** [comment] 2019-02-14 18:03
you may use the create function endpoints, specifying the image. documentation is here: http://petstore.swagger.io/?url=https://raw.githubusercontent.com/fnproject/fn/master/docs/swagger_v2.yml#/Fns/CreateFn

**Comment by denismakogon** [comment] 2019-02-14 18:17
> As I understand, fnproject/fnserver is an independent server providing routing, logging, queuing etc. For every app(collection of functions), a new docker container is spinned up.

well, technically it's not, each application is a set of functions, it's a record in database, that's it.
each function identified by a docker image with some RAM/CPU quotas.

on every call, Fn creates a function and ships the request to that and so on.
