### ISSUE TITLE
Exec format error (arm64)

### ISSUE THREAD

**Issue by DQvsRA** [fnproject/fn#431] opened 2017-10-17 10:00 UTC
I'm trying to run Fn on my arm64 board (Odroid c2). And that's what I've got.

![image](https://user-images.githubusercontent.com/442111/31658905-b2abc26a-b332-11e7-80a1-cdae98c256e0.png)

**Comment by hibooboo2** [comment] 2017-10-17 14:21
I would try installing from source. That would suit arm better. As right now our precompiled bins are not for arm64.

**Comment by hibooboo2** [comment] 2017-10-17 14:22
However you will run into other issues with arm. Such as the fact that the lang images by default are not arm.

**Comment by denismakogon** [comment] 2017-12-14 17:00
Closing this issue, because the problem is related to CLI, see referenced PR. If you think that you would like to have fn server binaries for ARM-based chips please reopen this issue.

**Closed by denismakogon** 2017-12-14 17:00 UTC
