### ISSUE TITLE
Hot path polls for container stats between calls

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#522] opened 2017-11-20 00:23 UTC
Docker stats are being polled during whole container lifecycle. But Fn should only care about max memory consumption during the specific call. Unfortunately, it's not enough to ask for max memory consumption from Docker, we should collect all stats within call and then find maximum among them.

**Comment by nigeldeakin** [comment] 2017-11-20 12:12
Currently docker stats relate to the running container, for as long as it is running. 

Adding a new set of stats which are specific to each individual invocation of a hot function sounds like a good idea. So I'd say the current behaviour is by design, but you have raised a good feature request.

**Comment by rdallman** [comment] 2017-11-20 20:05
these metrics could prove useful and the overhead of opening the docker stats stream is relatively high to the point of not being worth it. it's really easy to ignore the data points in between... closing

**Closed by rdallman** 2017-11-20 20:05 UTC
