### ISSUE TITLE
[Feature Request] Limit Function CPU usage

### ISSUE THREAD

**Issue by kuashe** [fnproject/fn#405] opened 2017-10-08 10:32 UTC
### Why ?

All FaaS (AWS , Google , Azure ) limit CPU usage of a function.

In my opinion it's critical to implement such feature . 
At the moment a single function **can exhaust an entire server** with 100% CPU utilization using all cores even if it's for a short period of time.

I think Google CPU to Memory Ratio is very coherent as a default setting

| Memory | CPU    |
|--------|--------|
| 128    | 200MHz |
| 256    | 400MHz |
| 512MB  | 800MHz |
| 1024MB | 1.4GHz |
| 2048MB | 2.4GHz |

### Proposition
- Limit container to only one thread utilization
- Add a default CPU to Memory function ratio 
- Add a parameter to define arbitrary CPU (in **Megahertz**) to Memory ratio

Links :
[How to limit a container CPU usage](https://docs.docker.com/engine/admin/resource_constraints/#cpu)
[GCloud Compute to Memory Ratio](https://cloud.google.com/functions/pricing#compute_time)
[GoLang CPU Megahertz and Cores count Lib](https://github.com/shirou/gopsutil)

**Comment by treeder** [comment] 2017-10-08 17:59
We currently use CPU shares so 1 function won't take the entire CPU if others  are running, they will all get an equal share. If there's only 1 running, then it gets 100% of the share.

**Comment by kuashe** [comment] 2017-10-08 19:26
Wouldn't this lead to un-consistent performance ?

When there is little or no traffic , the functions will execute really fast.
When there is a lot of traffic , functions would run much slower. 

Limiting CPU by default would help to predict performance of a server.

**Comment by rdallman** [comment] 2017-10-09 19:52
yep, it is inconsistent. but at least, it makes it not a __critical__ issue since we have this in place, and we won't exhibit the behavior that 1 function can exhaust an entire server if > 1 function exists on it and needs cpu, since they will share equally. 

we had some success running prod workloads like this on a different product in the past since it ends up getting better utilization when not at capacity, many users like this feature, though obviously it's ideal to run at capacity, we found that most of the time users are not running at 100% capacity on their clusters (only spikes). it also makes it much easier to size nodes if you only talk in terms of memory ;)

it would be nice if we exposed this, since right now it's not optional, so that operators could decide for themselves which strategy to use. and I agree that in running a full blown service (ala lambda) it's probably ideal to dole out MHz instead of using `cpu_share`, but in the operators running their own clusters (i.e. internal service at a company) many like the `cpu_share` strategy. anyway, +1 that it should be an option we expose. imagine this is easy to plumb into our docker init.

**Comment by rdallman** [comment] 2017-10-09 19:54
ah, since we are allowing user input on the `memory` stuff in the open source project, and cpu will likely be based off of that, this will likely come in as some kind of extension to scale based on memory, now that I hit enter it came to mind :)

**Comment by rdallman** [comment] 2017-10-09 21:40
Yea, the downside is it's not consistent -- the upside, sometimes you get turbo boost :). ultimately, yea, we leave it up to operators really is the goal (w/ sane defaults). 

I just mean that since users can specify e.g. `memory=711` and get 711MB, we need MHz of CPU to be a factor of that, and having fixed levels of cpu usage as proposed is similar in nature to the issue of building api wrappers around setting memory so that e.g. only `[256, 512]` are available whereas now `0 < memory < 8GB` any value in that range is valid. so what i'm getting at is that if we allow setting CPU MHz to containers at run time (part we need to add) then the rest of the policy decisions are up to extensions to implement (possible now, afaik) -- as proposed here. at least, it's not the responsibility of the fn server to have strict memory / cpu limit policies, users are expected to extend the api to add their policies (and our service version of this will do exactly that).

**Comment by kuashe** [comment] 2017-10-11 09:35
Yes , fn should offer option to set limits , then an API should be build on top of it to control CPU / Memory authorization , it's obviously not fn job to do this.

I'll add that an option for single threading would be great too.

**Comment by skinowski** [comment] 2018-01-03 19:56
How about the following proposal?

- New CPUQuota value in calls/routes. Default is zero (unlimited) (fallback to cpu_shares)
- CPUQuota is a value similar to percentage, eg. 20 means %20 of single cpu, %300 means 3 cpus.
- FN server handles CPU similar to memory, if a server has 8 CPUs, then we have total of 800 units.
- The available CPU per FN server can fed back to FN LB for LB decisions

CPU count is not perfect since different CPUs have different performance. But we have to assume some level of consistency in the fleet, so this proposal assumes CPUs in the fleet are somewhat similar in speed & architecture. (Same drawbacks apply to Mhz as well.)

This works well for servers with small amount of RAM with lots of CPU cores as well as servers with a lot of RAM but not many CPU cores. (And compatible if docker-in-docker is invoked with cpu limits.)

CPUQuota also very similar to 'cpus' flag for docker-run. But instead of a floating point number, we use integers to specify percentage. (0.2 cpus is same as 20 CPUQuota)

If docker-in-docker is configured with 'cpus' (or cpu_period and cpu_quota), then we can clamp our totals further based on this limit. This is similar to how we handle Memory limits today.

A fleet with mixed CPU counts is problematic, but with FN LB in front using available CPU metric to route to backends, this could be manageable.

Mixed workloads (unlimited CPUQuota calls mixed with non-zero CPUQuota calls) is also an issue, so operators has to keep an eye on that either by not allowing zero CPUQuota calls at all or only allowing zero CPUQuota calls (what we have today). I'm open to ideas for picking the right policy.

**Comment by rdallman** [comment] 2018-01-03 20:50
the biggest concern is, as pointed out, units doesn't directly map to some relatively static amount of CPU between different CPUs. to me, the issue is more to the user it's not really intuitive what 'CPU units' are. as a backend system for chopping up CPU, using units makes sense. even MHz is imperfect (as noted) between CPUs, but it seems more intuitive from a user perspective. mapping 'units' onto cores doesn't seem too far flung from chopping up cpus into MHz, and deriving capacity (for FN / FNLB to use) from X MHz used / Y MHz available; i.e. adding all the MHz together and deducting from that for each call seems to be about the same thing as units? at least, seems like we can translate a user specified MHz to basically what is proposed here with units. e.g. if a route has CPU=512 MHz and each core has 2.5 MHz we use 'cpus=.2' flag to docker run. does this break down in certain configurations?

**Comment by kuashe** [comment] 2018-01-03 20:57
> CPUQuota is a value similar to percentage, eg. 20 means %20 of single cpu, 300 means 3 cpus.
Great that enable single threading or multithreading 

> CPU count is not perfect since different CPUs have different performance.
Indeed , cpu count may vary depending on the provider ( virtualization etc... ) it's not fn responsability to determine that. Performance will vary from one machine to another , on the same machines/fleet it's likely to be very consistent .

> operators has to keep an eye on that either by not allowing zero CPUQuota calls at all or only allowing zero CPUQuota calls 
Indeed, in it's state current fn has no way to enforce entreprise policy so it's the operators job to create a service that will enforce either no CPU limit at all , or only CPU limited functions.

**Comment by skinowski** [comment] 2018-01-03 21:11
Mhz is not very different than units, but determining it is harder. With variable speed CPUs, we can't simply look at /proc/cpuinfo, but have to rely on utilities such as lscpu (or dig into how it determines this.) In comparison, CPU count is in go runtime. There are also exotic CPUs without Mhz, but not sure we would have to ever deal with those.

**Comment by skinowski** [comment] 2018-01-03 21:12
And also the docker & CFS scheduler (cpu_quota/cpu_period) maps nicely into CPU units.

**Comment by kuashe** [comment] 2018-01-03 21:15
I agree , cpu units is generally simpler . 
I think it's up to operators to provide documentation that maps units to MHZ .

Also Mhz can be confusing if using multiple cores at once .

**Comment by skinowski** [comment] 2018-01-03 21:19
FYI /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq is where Mhz information is for cpu 0.

**Comment by rdallman** [comment] 2018-01-03 21:23
mapping directly to docker's 'cpus' makes sense for our use case, yea. maybe 'cores'/'units'/'cpus' as a (rounded) float before decimal shifting seems a little more intuitive to me than a units=percentage (.2 vs 200), but I can see the merits of either way.

**Comment by skinowski** [comment] 2018-01-03 21:25
We can be fully docker compatible and just use float same as 'cpus' in that case.

**Comment by skinowski** [comment] 2018-01-03 21:40
Related issue: https://github.com/fnproject/fn/issues/497

**Comment by denismakogon** [comment] 2018-01-03 21:41
I do know that Fn runs on docker, but there's a chance to develop another COE driver, so, can someone explain how that would map to kubernetes, rkt or whatever people would want for Fn?

**Comment by skinowski** [comment] 2018-01-03 21:43
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu

Same floating point convention in k8s it looks like.

**Comment by skinowski** [comment] 2018-01-03 21:52
Seems like rkt and k8s can use both float or msec format.

**Comment by skinowski** [comment] 2018-01-05 06:39
work-in-progress #642

**Comment by skinowski** [comment] 2018-01-12 21:28
#642 now merged in.

**Closed by skinowski** 2018-01-12 21:28 UTC
Labels: feature request, for discussion
