### ISSUE TITLE
Removing 'timeout' from func.yaml does not take effect

### ISSUE THREAD

**Issue by abhirockzz** [fnproject/fn#1289] opened 2018-10-31 08:30 UTC
**Description**

**Steps to reproduce the issue:**
1. `fn init --runtime go --name test` and `fn -v deploy --app testapp --local`
2. `fn inspect fn testapp test` shows `timeout` value as 30 - this is fine 
3. update `timeout` in func.yaml (to 60) and re-deploy the app. `fn inspect fn testapp test` shows `timeout` value as 60 - so far so good
4. remove the `timeout` from `func.yaml` and re-deploy the app

**Describe the results you received:**

`fn inspect fn testapp test` still shows `timeout` value as 60

**Describe the results you expected:**

`fn inspect fn testapp test` should show `timeout` value as 30 (default value)

**Output of `fn version` (CLI command):**

```
Client version: 0.5.23 is not latest: 0.5.26
```

**Additional environment details (OSX, Linux, flags, etc.):**
Linux

**Comment by denismakogon** [comment] 2018-10-31 10:06
Hi, your assumption is quite incorrect. Because when you delete the timeout from the `func.yaml` and calling `fn deploy` you're basically saying to Fn update my function with no timeout changes, that's why the timeout will remain as it was from the last update.
So, IMHO, it's not a bug but expected behaviour.

**Comment by rdallman** [comment] 2018-10-31 17:20
this is a dupe of https://github.com/fnproject/fn/issues/803 - thanks for filing, feel free to add to discussion there, it's something we've/we're considering solutions to

**Closed by rdallman** 2018-10-31 17:20 UTC
