### ISSUE TITLE
separate LogStore logs aren't cleaned up upon app deletion

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#587] opened 2017-12-12 13:47 UTC
Steps to reproduce:
1. Deploy function.
2. Call function.
```
curl -v localhost:8080/r/testapp/test-fdk-python -d '{"name":"john"}'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /r/testapp/test-fdk-python HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 15
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 15 out of 15 bytes
< HTTP/1.1 200 OK
< Content-Length: 10
< Content-Type: text/plain; charset=utf-8
< Fn_call_id: 01C15DMDP3A7WG200000000000
< Xxx-Fxlb-Wait: 609.713779ms
< Date: Tue, 12 Dec 2017 13:26:22 GMT
< 
* Connection #0 to host localhost left intact
```
Remember call ID: `01C15DMDP3A7WG200000000000`
3. Delete an app
4. Do the steps 1 and 2 again.
5. List calls
```
fn calls list testapp

ID: 01C15EF78FA7WG600000000000
App: testapp
Route: /test-fdk-python
Created At: 2017-12-12T13:26:21.199Z
Started At: 2017-12-12T13:26:21.809Z
Completed At: 2017-12-12T13:26:21.836Z
Status: success
```
6. Go to minio UI
You'd see that logs are still there:
<img width="1440" alt="screen shot 2017-12-12 at 3 32 22 pm" src="https://user-images.githubusercontent.com/3034091/33887237-ce490d20-df51-11e7-8fd4-7a47ae5fa990.png">

7. Try to get call log from step 3

```
fn logs get testapp 01C15DMDP3A7WG200000000000
{'host': 'localhost:8080', 'accept': '*/*', 'fn_app_name': 'testapp', 'fn_call_id': '01C15DMDP3A7WG200000000000', 'fn_format': 'http', 'fn_memory': '128', 'fn_method': 'GET', 'fn_param_app': 'testapp', 'fn_param_route': '/test-fdk-python', 'fn_path': '/test-fdk-python', 'fn_request_url': 'http://localhost:8080/r/testapp/test-fdk-python', 'fn_type': 'sync', 'user-agent': 'curl/7.54.0'}
environ({'PATH': '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'HOSTNAME': 'cb9060945294', 'FN_PATH': '/test-fdk-python', 'FN_MEMORY': '128', 'FN_TYPE': 'sync', 'FN_FORMAT': 'http', 'FN_APP_NAME': 'testapp', 'LANG': 'C.UTF-8', 'GPG_KEY': '0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D', 'PYTHON_VERSION': '3.6.2', 'PYTHON_PIP_VERSION': '9.0.1', 'HOME': '/root'})

```

So, the log is still there. It happens because of the way we delete calls and logs. Fn stores call in SQL store when we attempt to delete an app, Fn attempts to delete routes, calls and logs within a single transaction without use of datastore API just [raw SQL](https://github.com/fnproject/fn/blob/master/api/datastore/sql/sql.go#L333).

**Comment by rdallman** [comment] 2017-12-12 20:03
the name of this issue seems misleading. this issue seems to raise that we aren't deleting logs (#473 notes this, because we don't have a cleaner), not the logs aren't going anywhere? it seems like the issue is that the logs went somewhere and stayed there. i'll edit, but feel free to re-edit if this is wrong. in any case it seems like this is a double issue with #483 so kinda leaning towards closing (re-open if i misinterpreted)

**Comment by rdallman** [comment] 2017-12-12 20:06
I see one potential issue is that re-creation of new app/route gets logs for old app/route, so we should figure out a way to mark those logs as deleted because relying on the cleaner won't fix this one. i think deletion in minio will be very expensive with a lot of logs, since we're shoving all in one bucket. maybe we should consider making per-app and per-route buckets (managability of this is more challenging) since I imagine bucket deletion is a quick operation.

**Comment by denismakogon** [comment] 2017-12-12 20:30
+1 for the per-app bucket

**Comment by rdallman** [comment] 2017-12-12 21:37
there's kind of no way we can do this atomically, sadly (the case for app/route ids, meh). will think about it. also i don't think nested buckets are a thing (route bucket inside of app bucket inside of one-much-larger bucket)

**Comment by denismakogon** [comment] 2017-12-12 23:06
@rdallman Can you explain why that is not the case to have one app bucket with log entries?

As far as I understand the source of the problem here, is that we don't have the cleaner for logs for certain reasons (no matter what they are at this moment). So, we want to make the simple plan for storing logs, I would say that best option here is to create an app bucket as the placeholder for logs. I think it would work for us at least for the one reason: at this moment we have only 1 API endpoint that retrieves logs from the log store.
So, tell me why deleting the whole app bucket would not work for Fn? Maybe I am missing something?

**Comment by rdallman** [comment] 2017-12-12 23:52
i mean right now they are all in one big bucket and searchable by app + call id, so you could prefix search and find all under an app, there's not really an addressability issue and what we have works fine except in this delete-then-recreate case. the app bucket gives us no sugar other than, it will be fast to delete a bucket, but there's still a hole regardless.

ultimately, our schema in minio does not matter whatsoever, there is no way we can atomically delete everything in the sql database for an app or route and also delete everything in minio for that app or route. it's just not really possible to do this in one transaction. we can basically pick whether we want to delete all the stuff in sql first or all the stuff in minio first, we can't do both, and we can always end up in a state where one exists and the other doesn't even though we wanted to delete both. so, what we need to do, is either change the way we're addressing the resources in minio with something that won't be there on re-creation (app and route alone are not sufficient) or find a way to atomically mark these as deleted such that whatever apis we have can know that we cannot return resources that may be found in minio because they've been marked as deleted. 

anyway, moving to app bucket doesn't fix anything. i can't think of anything atm that will close this hole that doesn't completely suck (checking db for every log request).

**Closed** 2019-04-16 19:35 UTC
Labels: bug, waiting
