### ISSUE TITLE
regression: timeout errors have increased in normal operation

### ISSUE THREAD

**Issue by mjg123** [fnproject/fn#669] opened 2018-01-10 14:40 UTC
When running locally this error is seen intermittently:

```
{"error":{"message":"Timed out - server too busy"}}
```

This causes a 5xx error to the caller, but I suspect this is a recent regression as it didn't use to happen, and the server isn't actually very busy.

Seen by @carimura @shaunsmith

**Comment by mjg123** [comment] 2018-01-10 14:42
Possibly related to this patch? https://github.com/fnproject/fn/commit/14789ab

**Comment by rdallman** [comment] 2018-01-10 17:57
we could curtail the error message to just say 'timed out', it's not always the case that the server is too busy, we return this if it takes too long to pull the image, for example. we can't get rid of timeouts, but the regression here is we're giving more than we're used to I guess (changing issue name to that). the thinking is in the future a load balancer can retry these. anyway, can try to repro, but if it's image pulling, which I suspect, all we can really do is change the error message?

**Comment by skinowski** [comment] 2018-01-10 18:52
Can I have some info on this?

hot/cold? mixed case?
what is the load? how many req/sec? could you describe the case please?
what's the env? memory?

**Comment by carimura** [comment] 2018-01-10 18:54
anecdotally i think this has been coming up a bunch... one from community, from others on team, and from me yesterday (although I *was* logged into zoom while demo'ing).

I was just running Vista in Flow mode (locally) and got it.

**Comment by rdallman** [comment] 2018-01-10 19:03
corollary: maybe we should consider raising the default timeout if things are too tight for everyone. 

since we're exposed through an http endpoint, clients have to retry using their http client, so we can't just add retries in seamlessly in client libraries (since they don't exist for this endpoint). other ux ideas? we will never not have timeouts, need to make it look less like a bug to users somehow.

**Comment by skinowski** [comment] 2018-01-10 19:29
Hmm, my latest timeout adjustment #658  could be a factor. Now, the timeouts are more accurate since now, it includes couple more DB queries which were not being factored before.

**Comment by skinowski** [comment] 2018-01-10 19:33
#658 now starts the timer in GetCall() while before #658 the timers started in Submit(), after FromRequest() execution which includes two DB queries.

**Comment by skinowski** [comment] 2018-01-10 22:34
Closing this, let's reopen if we observe it again.

**Comment by jan-g** [comment] 2018-01-11 11:32
Reopening this: we are still seeing it (and can provoke it at will); this is blocking fdj-java ci.

It's possible to duplicate what the CI does by judiciously running integration-tests/run-local.sh, but to talk you through it:

- spawns the latest released fn server using /var/run/docker.sock passthrough

- spawns the latest flow server

- runs all integration tests in parallel. These build and deploy, then invoke, a bunch of functions; the most heavy-weight of these can be found in `integration-tests/main/test-4` (although it's not necessarily the only one that'll fail). The error traces come from the flow server (usually) as it tries to spawn additional hot-function calls to handle the flows. In total that test will spawn around 100 stages - these are all very short-lived and were typically multiplexed across one to two dozen containers.

These tests used to work reliably; this is a regression. It's possible that something else is causing the issue - ISTR we dropped the 100ms "wait and see" before launching a new hot container when we are at capacity. Given the short-lived nature of flow orchestration steps (and all the things that test-4 fall into this category), it's entirely possible that that delay was enabling the same workload to be serviced with far fewer hot containers.

**Comment by mjg123** [comment] 2018-01-11 11:43
Logs which show the failure:

https://circleci.com/gh/fnproject/fdk-java/762
https://circleci.com/gh/fnproject/fdk-java/763
https://circleci.com/gh/fnproject/fdk-java/764

("too busy" errors cause build failure in 100% of our recent builds)

**Comment by skinowski** [comment] 2018-01-11 19:01
ok, I see the issue here... I'll submit a fix.

**Comment by skinowski** [comment] 2018-01-11 22:11
Fix: #677 is now in.. Closing it again, we can reopen.

**Closed by skinowski** 2018-01-11 22:11 UTC
Labels: bug
