### ISSUE TITLE
[Code duplication] Extract protocols to sub-project/package

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#964] opened 2018-04-30 17:30 UTC
Here's the thing. We have at least 3 written on Go different projects where we use marshalling/unmarshalling of the protocol's frame:
 - CLI
 - Fn
 - FDK-go

In order to keep them consistent, we might need to put protocols into a sub-package (like `fnext`) or sub-project (it's up to us decide hopefully).

**Comment by rdallman** [comment] 2018-04-30 17:44
cli and fdk use same structs right?

we tried having the server rely on fdk models but it didn't work very well, it's a strange dependency since we have to update the swagger to generate the models to import the changed models and then we're stuck with some weird version of the fdk we're importing that doesn't exist in the released fdk until we land a feature. also for the server we're making judicious use of `db:""` struct tags which don't make sense in fdk models.

so, seems like we're at optimal already for this? i take it we want to eliminate issues like https://github.com/fnproject/fdk-go/issues/23#issuecomment-385472882 but that has a lot of context around what went wrong (can't use swagger to switch on content type, change wasn't made with compatibility in mind, cli doesn't seem to stay up to date with fdk updates). in this case, i don't think it's a good idea to rope in fn server to this discussion.

**Comment by rdallman** [comment] 2018-04-30 17:56
rewriting to say same-ish thing, this is a dupe of https://github.com/fnproject/cli/issues/156 btw. 

fn server and CLI (sender) play a different role than the fdk (receiver), for one, i don't think those need to be co-located. importing fn into cli seems like it won't go well, this will be hard to maintain. after we have cloud events i don't think there's really a lot of complications around all our protocol stuff (#957). right now it's really bad since we have 4 protocols basically. i foresee us maybe importing some kind of package like `github.com/fnproject/cloudevent` (or maybe official one some day) but that won't handle the STDIN/STDOUT, it will just have struct definitions, we can pretty easily marshal / unmarshal that struct to/from stdin/stdout. anyway i think the issue is mostly to do #785 (get rid of all formats but cloud event), then all we're left with is the cli and the server are both constructing docker images and there's some duplicate code there. maybe one day we figure out how to extract that, but i'm not sure the tradeoffs are worth it anyway (managing 3rd party dep is no fun).

**Comment by denismakogon** [comment] 2018-04-30 18:05
Sorry, you've posted just a minute before i've posted PR for FDK https://github.com/fnproject/fdk-go/pull/24 =/

**Comment by rdallman** [comment] 2018-11-08 21:54
stale

**Closed by rdallman** 2018-11-08 21:54 UTC
Labels: good first issue, help wanted
